/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/J5aWUUfIG2q
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { IBM_Plex_Sans } from 'next/font/google'

ibm_plex_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"

export function billingPage() {
  return (
    <div className="flex flex-col min-h-screen w-full">
      <header className="bg-background border-b">
        <nav className="flex items-center justify-between py-4">
          <div className="flex items-center gap-4">
            <Link href="#" className="flex items-center gap-2" prefetch={false}>
              <MountainIcon className="h-6 w-6" />
              <span className="text-lg font-bold">SimplyTalk.ai</span>
            </Link>
          </div>
          <div className="flex items-center gap-4">
            <Link
              href="#"
              className="group flex items-center gap-2 px-4 py-2 rounded-md bg-primary text-primary-foreground transition-colors hover:bg-primary/90"
              prefetch={false}
            >
              <UsersIcon className="h-5 w-5" />
              <span>Assistants</span>
            </Link>
            <Link
              href="#"
              className="group flex items-center gap-2 px-4 py-2 rounded-md bg-primary text-primary-foreground transition-colors hover:bg-primary/90"
              prefetch={false}
            >
              <PlusIcon className="h-5 w-5 text-primary-foreground" />
              <span>Create new Assistant</span>
            </Link>
            <Link
              href="#"
              className="group flex items-center gap-2 px-4 py-2 rounded-md bg-primary text-primary-foreground transition-colors hover:bg-primary/90"
              prefetch={false}
            >
              <CreditCardIcon className="h-5 w-5 text-primary-foreground" />
              <span>Billing</span>
            </Link>
            <Link
              href="#"
              className="group flex items-center gap-2 px-4 py-2 rounded-md transition-colors hover:bg-muted hover:text-foreground"
              prefetch={false}
            >
              <SettingsIcon className="h-5 w-5 text-muted-foreground group-hover:text-foreground" />
              <span>Settings</span>
            </Link>
          </div>
        </nav>
      </header>
      <main className="flex-1 p-4 sm:p-6">
        <section className="mb-6">
          <div className="flex items-center justify-between">
            <h2 className="text-2xl font-bold">Billing</h2>
          </div>
          <div className="mt-4 rounded-md border bg-background p-4">
            <div className="grid gap-6">
              <div>
                <h3 className="text-lg font-bold">Current Plan Details</h3>
                <div className="mt-2 grid gap-2">
                  <div className="flex items-center justify-between">
                    <span>Plan:</span>
                    <span>Pro</span>
                  </div>
                  <div className="flex items-center justify-between">
                    <span>Usage:</span>
                    <span>500/1000 minutes</span>
                  </div>
                  <div className="flex items-center justify-between">
                    <span>Next Billing Date:</span>
                    <span>June 1, 2023</span>
                  </div>
                </div>
              </div>
              <div>
                <h3 className="text-lg font-bold">Billing History</h3>
                <div className="mt-2 grid gap-2">
                  <div className="flex items-center justify-between">
                    <div>
                      <div className="font-medium">May 1, 2023</div>
                      <div className="text-sm text-muted-foreground">Invoice #123</div>
                    </div>
                    <div className="text-right">
                      <div className="font-medium">$99.00</div>
                      <div className="text-sm text-muted-foreground">Paid</div>
                    </div>
                  </div>
                  <div className="flex items-center justify-between">
                    <div>
                      <div className="font-medium">April 1, 2023</div>
                      <div className="text-sm text-muted-foreground">Invoice #122</div>
                    </div>
                    <div className="text-right">
                      <div className="font-medium">$99.00</div>
                      <div className="text-sm text-muted-foreground">Paid</div>
                    </div>
                  </div>
                  <div className="flex items-center justify-between">
                    <div>
                      <div className="font-medium">March 1, 2023</div>
                      <div className="text-sm text-muted-foreground">Invoice #121</div>
                    </div>
                    <div className="text-right">
                      <div className="font-medium">$99.00</div>
                      <div className="text-sm text-muted-foreground">Paid</div>
                    </div>
                  </div>
                </div>
              </div>
              <div className="flex justify-end">
                <Button
                  onClick={() => (window.location.href = "https://dashboard.stripe.com/test/customers/cus_123/portal")}
                >
                  Manage Subscription
                </Button>
              </div>
              <div>
                <h3 className="text-lg font-bold">Top-Up Options</h3>
                <div className="mt-2 grid grid-cols-1 gap-4 sm:grid-cols-2 md:grid-cols-3">
                  <Card>
                    <CardContent>
                      <div className="flex items-center justify-between">
                        <div>
                          <div className="text-2xl font-bold">500 minutes</div>
                          <div className="text-muted-foreground">$40</div>
                        </div>
                        <Button>Buy</Button>
                      </div>
                    </CardContent>
                  </Card>
                  <Card>
                    <CardContent>
                      <div className="flex items-center justify-between">
                        <div>
                          <div className="text-2xl font-bold">1000 minutes</div>
                          <div className="text-muted-foreground">$70</div>
                        </div>
                        <Button>Buy</Button>
                      </div>
                    </CardContent>
                  </Card>
                  <Card>
                    <CardContent>
                      <div className="flex items-center justify-between">
                        <div>
                          <div className="text-2xl font-bold">2000 minutes</div>
                          <div className="text-muted-foreground">$120</div>
                        </div>
                        <Button>Buy</Button>
                      </div>
                    </CardContent>
                  </Card>
                  <Card>
                    <CardContent>
                      <div className="flex items-center justify-between">
                        <div>
                          <div className="text-2xl font-bold">3000 minutes</div>
                          <div className="text-muted-foreground">$160</div>
                        </div>
                        <Button>Buy</Button>
                      </div>
                    </CardContent>
                  </Card>
                  <Card>
                    <CardContent>
                      <div className="flex items-center justify-between">
                        <div>
                          <div className="text-2xl font-bold">5000 minutes</div>
                          <div className="text-muted-foreground">$250</div>
                        </div>
                        <Button>Buy</Button>
                      </div>
                    </CardContent>
                  </Card>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}

function CreditCardIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="14" x="2" y="5" rx="2" />
      <line x1="2" x2="22" y1="10" y2="10" />
    </svg>
  )
}

function MountainIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}

function PlusIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  )
}

function SettingsIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z" />
      <circle cx="12" cy="12" r="3" />
    </svg>
  )
}

function UsersIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
      <circle cx="9" cy="7" r="4" />
      <path d="M22 21v-2a4 4 0 0 0-3-3.87" />
      <path d="M16 3.13a4 4 0 0 1 0 7.75" />
    </svg>
  )
}
